#!/usr/bin/env node
/**
 * OPH-300 — carries the sync push contract across the language boundary.
 *
 * The server's field tables decide which keys a mutation may carry: one key it
 * does not know and the whole mutation is refused. The client had no way to see
 * that list, so it drifted — `fromTaskId` was added to the app's `task_series`
 * patch and every repeat the app ever started came back `SYNC_UNKNOWN_FIELD`
 * for six weeks (OPH-299), with 796 API and 1598 app tests green throughout.
 *
 * This script is the missing half: it reads `SYNC_ENTITY_FIELDS` — the one
 * place the server declares the contract — and writes it as Dart the client
 * asserts against on every `enqueueMutation`. `--check` fails when the two have
 * drifted, which is what makes the generated file impossible to forget.
 *
 *   node scripts/sync/fields.mjs           # write
 *   node scripts/sync/fields.mjs --check   # fail on drift (CI)
 *
 * The emitted layout is NOT the contract. Dart's tall-style formatter collapses
 * a short collection onto one line whether or not it has a trailing comma, and
 * CI gates `dart format` separately — so `--write` hands the file to the
 * formatter afterwards, and `--check` reads the KEYS back out of the Dart
 * rather than comparing bytes. A gate that failed on whitespace would be a gate
 * people learn to ignore.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { SYNC_ENTITY_FIELDS } from '../../apps/api/src/routes/sync.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const TARGET = resolve(ROOT, 'apps/app/lib/src/sync/sync_fields.g.dart');

/** `{ entityType: { all: [...], createOnly: [...], updateOnly: [...] } }`. */
function contract() {
  const out = {};
  for (const [type, fields] of Object.entries(SYNC_ENTITY_FIELDS)) {
    const all = Object.keys(fields).sort();
    out[type] = {
      all,
      createOnly: all.filter((k) => fields[k].createOnly === true),
      updateOnly: all.filter((k) => fields[k].updateOnly === true),
    };
  }
  return out;
}

const dartSet = (keys, indent) =>
  keys.length === 0
    ? '<String>{}'
    : `{\n${keys.map((k) => `${indent}  '${k}',`).join('\n')}\n${indent}}`;

function render() {
  const spec = contract();
  const types = Object.keys(spec).sort();

  const entries = types
    .map((type) => {
      const { all, createOnly, updateOnly } = spec[type];
      return [
        `  '${type}': AwSyncEntityFields(`,
        `    all: ${dartSet(all, '    ')},`,
        `    createOnly: ${dartSet(createOnly, '    ')},`,
        `    updateOnly: ${dartSet(updateOnly, '    ')},`,
        `  ),`,
      ].join('\n');
    })
    .join('\n');

  const total = types.reduce((n, t) => n + spec[t].all.length, 0);

  return `// GENERATED BY scripts/sync/fields.mjs — DO NOT EDIT BY HAND.
//
// Source of truth: \`SYNC_ENTITY_FIELDS\` in apps/api/src/routes/sync.js.
// Regenerate with \`npm run gen:sync-fields\`; \`npm run check:sync-fields\`
// fails the build when this file and the server have drifted apart.
//
// ${types.length} entities, ${total} fields (OPH-300).

import 'sync_contract.dart';

/// Which keys the server accepts in a push patch, per entity type.
const Map<String, AwSyncEntityFields> kAwSyncFields = {
${entries}
};
`;
}

/**
 * Reads the contract back OUT of the generated Dart.
 *
 * Deliberately not a byte comparison against `render()`. `dart format` owns the
 * layout of that file and CI gates it separately (`--set-exit-if-changed`), so
 * a byte check would fail the moment the formatter collapsed a short set onto
 * one line — a disagreement about whitespace reported as a broken contract.
 * What this gate is for is whether the two sides agree on the KEYS.
 */
function parseDart(source) {
  const out = {};
  const blocks = [...source.matchAll(/'([a-z_]+)':\s*AwSyncEntityFields\(/g)];
  for (const [i, match] of blocks.entries()) {
    const start = match.index + match[0].length;
    const end = i + 1 < blocks.length ? blocks[i + 1].index : source.length;
    const body = source.slice(start, end);
    const setOf = (name) => {
      const at = body.indexOf(`${name}:`);
      if (at === -1) return null;
      const open = body.indexOf('{', at);
      const close = body.indexOf('}', open);
      if (open === -1 || close === -1) return null;
      return [...body.slice(open, close).matchAll(/'([^']+)'/g)].map((m) => m[1]).sort();
    };
    out[match[1]] = {
      all: setOf('all'),
      createOnly: setOf('createOnly'),
      updateOnly: setOf('updateOnly'),
    };
  }
  return out;
}

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

if (process.argv.includes('--check')) {
  let current = null;
  try {
    current = readFileSync(TARGET, 'utf8');
  } catch {
    console.error(`✗ sync fields: ${TARGET} is missing — run \`npm run gen:sync-fields\`.`);
    process.exit(1);
  }

  const server = contract();
  const client = parseDart(current);
  const problems = [];

  for (const type of Object.keys(server)) {
    if (!client[type]) {
      problems.push(`  ${type}: the client contract does not know this entity at all`);
      continue;
    }
    for (const part of ['all', 'createOnly', 'updateOnly']) {
      if (same(server[type][part], client[type][part])) continue;
      const missing = server[type][part].filter((k) => !(client[type][part] ?? []).includes(k));
      const extra = (client[type][part] ?? []).filter((k) => !server[type][part].includes(k));
      problems.push(
        `  ${type}.${part}:` +
          (missing.length ? ` missing ${missing.join(', ')}` : '') +
          (extra.length ? ` unknown to the server: ${extra.join(', ')}` : ''),
      );
    }
  }
  for (const type of Object.keys(client)) {
    if (!server[type]) problems.push(`  ${type}: the server declares no such entity`);
  }

  if (problems.length > 0) {
    console.error(
      '✗ sync fields: the client contract has drifted from the server.\n' +
        problems.join('\n') +
        '\n  Run `npm run gen:sync-fields` and commit apps/app/lib/src/sync/sync_fields.g.dart.',
    );
    process.exit(1);
  }
  const n = Object.keys(server).length;
  console.log(`✓ sync fields: client and server agree on all ${n} entity contracts`);
} else {
  writeFileSync(TARGET, render());
  // `dart format` owns this file's layout — emit, then let it have the last
  // word, so a freshly generated file never fails CI's formatting gate.
  const dart = spawnSync('dart', ['format', TARGET], { stdio: 'ignore' });
  const formatted = dart.status === 0 ? ' (dart-formatted)' : ' (dart not on PATH — run `dart format` before committing)';
  console.log(`✓ wrote ${TARGET}${formatted}`);
}
