// GENERATED BY scripts/sync/fields.mjs — DO NOT EDIT BY HAND.
//
// Source of truth: `SYNC_ENTITY_FIELDS` in apps/api/src/routes/sync.js.
// Regenerate with `npm run gen:sync-fields`; `npm run check:sync-fields`
// fails the build when this file and the server have drifted apart.
//
// 9 entities, 62 fields (OPH-300).

import 'sync_contract.dart';

/// Which keys the server accepts in a push patch, per entity type.
const Map<String, AwSyncEntityFields> kAwSyncFields = {
  'checklist_item': AwSyncEntityFields(
    all: {'isDone', 'sortOrder', 'taskId', 'title'},
    createOnly: {'taskId'},
    updateOnly: <String>{},
  ),
  'folder': AwSyncEntityFields(
    all: {'name', 'parentId'},
    createOnly: <String>{},
    updateOnly: <String>{},
  ),
  'note': AwSyncEntityFields(
    all: {
      'contentDelta',
      'contentFormat',
      'contentMarkdown',
      'isArchived',
      'isPinned',
      'projectId',
      'title',
    },
    createOnly: <String>{},
    updateOnly: <String>{},
  ),
  'project': AwSyncEntityFields(
    all: {
      'colorRgb',
      'description',
      'dueAt',
      'icon',
      'isFavorite',
      'name',
      'readmeNoteId',
      'sortOrder',
      'startAt',
      'status',
    },
    createOnly: <String>{},
    updateOnly: <String>{},
  ),
  'quick_link': AwSyncEntityFields(
    all: {
      'colorRgb',
      'emoji',
      'kind',
      'orderedIds',
      'targetId',
      'title',
      'url',
    },
    createOnly: {'kind', 'targetId', 'url'},
    updateOnly: {'orderedIds'},
  ),
  'reminder': AwSyncEntityFields(
    all: {'status'},
    createOnly: <String>{},
    updateOnly: {'status'},
  ),
  'tag': AwSyncEntityFields(
    all: {'colorRgb', 'icon', 'name'},
    createOnly: <String>{},
    updateOnly: <String>{},
  ),
  'task': AwSyncEntityFields(
    all: {
      'actualMinutes',
      'alarmsMutedAt',
      'calendarMirrorEnabled',
      'colorRgb',
      'description',
      'dueAt',
      'estimatedMinutes',
      'isUrgent',
      'parentTaskId',
      'priority',
      'projectId',
      'remindAt',
      'requiresAcknowledgement',
      'scheduledEndAt',
      'scheduledStartAt',
      'seriesScope',
      'snoozedUntil',
      'sortOrder',
      'startAt',
      'status',
      'tagIds',
      'timezone',
      'title',
    },
    createOnly: <String>{},
    updateOnly: {'seriesScope', 'snoozedUntil'},
  ),
  'task_series': AwSyncEntityFields(
    all: {'anchorAt', 'fromTaskId', 'rule', 'template', 'timezone'},
    createOnly: {'fromTaskId'},
    updateOnly: <String>{},
  ),
};
