#!/usr/bin/env node
/**
 * OPH-317 — the platform table in `docs/NOTIFICATIONS.md` §3 is rendered from
 * the app's own declaration, and CI fails when they part company.
 *
 * ── THE FAILURE THIS ANSWERS ──────────────────────────────────────────────
 *
 * §3 said the web "additionally needs Notification permission; treat as
 * best-effort", and no line of code asked for that permission. Nothing was
 * broken — a document and a binary simply disagreed, for months, and the
 * disagreement is what issue #16 turned out to be. OPH-313 fixed that one
 * instance; this closes the class.
 *
 * ── WHY IT READS DART AND NOT A FIXTURE ───────────────────────────────────
 *
 * `kNotificationMatrix` is not written for this script: `AwPushMessaging` asks
 * it whether the platform can hold a token before it asks the plugin for one,
 * so a row is the code's own answer rather than a note about it. The Dart test
 * (`platform_matrix_test.dart`) checks the declaration against behaviour; this
 * checks the document against the declaration. Neither side is the only
 * witness — the shape `check:push-payload` uses, with the DOC as the policy
 * file.
 *
 *   node scripts/notifications/matrix.mjs           # check (CI)
 *   node scripts/notifications/matrix.mjs --write   # re-render the table
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SOURCE = resolve(ROOT, 'apps/app/lib/src/notifications/platform_matrix.dart');
const DOC = resolve(ROOT, 'docs/NOTIFICATIONS.md');

const BEGIN = '<!-- notify-matrix:begin -->';
const END = '<!-- notify-matrix:end -->';

/** Reads the `NotificationPlatform(...)` entries out of the Dart declaration. */
function rows() {
  const dart = readFileSync(SOURCE, 'utf8');
  const list = dart.slice(
    dart.indexOf('const kNotificationMatrix'),
    dart.indexOf('/// The row for a registry platform id'),
  );
  const out = [];
  for (const block of list.split('NotificationPlatform(').slice(1)) {
    const field = (name) =>
      new RegExp(name + ':\\s*([^,\\n]+)').exec(block)?.[1]?.trim() ?? null;
    const push = field('serverPush');
    out.push({
      id: field('id')?.replace(/'/g, ''),
      gateway: field('gateway')?.replace('NotificationGatewayKind.', ''),
      localSchedule: field('localSchedule') === 'true',
      alarmKit: field('alarmKit') === 'true',
      serverPush: push === 'null' ? null : push?.replace(/'/g, ''),
      inAppScreen: field('inAppScreen') === 'true',
    });
  }
  if (out.length === 0 || out.some((r) => !r.id || !r.gateway)) {
    console.error('✗ notify matrix: could not read the declaration in ' + SOURCE);
    process.exit(1);
  }
  return out;
}

const yes = (value) => (value ? '✅' : '—');

function render(matrix) {
  const lines = [
    BEGIN,
    '',
    '<!-- Generated by `npm run check:notify-matrix -- --write` from',
    '     apps/app/lib/src/notifications/platform_matrix.dart. Edit the Dart, not this. -->',
    '',
    '| Platform | Gateway | Schedules locally | AlarmKit | Server push | In-app ring screen |',
    '| -------- | ------- | ----------------- | -------- | ----------- | ------------------ |',
  ];
  for (const row of matrix) {
    lines.push(
      '| ' +
        [
          row.id,
          row.gateway,
          yes(row.localSchedule),
          yes(row.alarmKit),
          row.serverPush ?? '—',
          yes(row.inAppScreen),
        ].join(' | ') +
        ' |',
    );
  }
  lines.push('', END);
  return lines.join('\n');
}

const doc = readFileSync(DOC, 'utf8');
const matrix = rows();
const table = render(matrix);

const start = doc.indexOf(BEGIN);
const end = doc.indexOf(END);

if (process.argv.includes('--write')) {
  if (start < 0 || end < 0) {
    console.error('✗ notify matrix: ' + DOC + ' has no markers to write between.');
    process.exit(1);
  }
  writeFileSync(DOC, doc.slice(0, start) + table + doc.slice(end + END.length));
  console.log('✓ notify matrix: rewrote the table in ' + DOC);
  process.exit(0);
}

if (start < 0 || end < 0) {
  // The state §3 was in before this gate existed: prose, and no table at all.
  // Silence here would be the whole bug, so it is the loudest failure.
  console.error(
    '✗ notify matrix: docs/NOTIFICATIONS.md §3 has no generated table.\n\n' +
      '  §3 is where the app tells users what each platform can do about a\n' +
      '  reminder, and it described a web permission flow that did not exist\n' +
      '  for months (issue #16). It carries a rendered table now:\n\n' +
      '    npm run check:notify-matrix -- --write',
  );
  process.exit(1);
}

if (doc.slice(start, end + END.length) === table) {
  console.log(
    '✓ notify matrix: §3 matches the app declaration (' + matrix.length + ' platforms)',
  );
  process.exit(0);
}

console.error(
  '✗ notify matrix: docs/NOTIFICATIONS.md §3 no longer matches the code.\n\n' +
    '  The table is rendered from `kNotificationMatrix`, which is what\n' +
    '  `AwPushMessaging` actually obeys — so a difference here means the\n' +
    '  document claims a platform does something the build does not do, or the\n' +
    '  other way round. That is issue #16, and it went unnoticed for months.\n\n' +
    '  Change the Dart if the behaviour changed, then:\n' +
    '    npm run check:notify-matrix -- --write',
);
process.exit(1);
